name: Build and Deploy Node.js app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: 'Set up Node.js'
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: 'Install Server Dependencies'
        run: npm install
        working-directory: ./server

      - name: 'Install Client Dependencies'
        run: npm install
        working-directory: ./client

      - name: 'Build the React app'
        run: npm run build
        working-directory: ./client

      - name: Copy React build files to server's public directory
        run: |
          mkdir -p ./server/public
          cp -r ./client/build/* ./server/public/

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'McNacToDoApp'
          publish-profile: ${{ secrets.azurePublishSettings }}
          package: ./server

